### ISSUE TITLE
Clarification: It seems the services is supposed to be a lead-ins

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Ascot-Signs#10]
1. Should the services links to a services single page?
![image](https://cloud.githubusercontent.com/assets/12888048/12254299/f60e2bcc-b921-11e5-94d9-1a3b9a37e121.png)
![image](https://cloud.githubusercontent.com/assets/12888048/12253392/571dfab2-b91a-11e5-8c01-ead5fb010a02.png)
![image](https://cloud.githubusercontent.com/assets/12888048/12254266/b2cd89ac-b921-11e5-9ba4-ad13450c388f.png)

2. Homepage lead-ins, individual post that link to a single page or page link?
It seems that the items displayed in front end are the Signage and Film Glass & Wall Graphics posts items.
![image](https://cloud.githubusercontent.com/assets/12888048/12254028/6e11f214-b91f-11e5-8c62-282105a7844a.png)

**Comment by romatitan** [comment]
It seems that the items displayed in front end are the Signage and Film Glass & Wall Graphics posts items.

**Comment by ganesh-titan** [comment]
FYI : Scope has been updated. yes, it should links to a page

**Comment by romatitan** [comment]
@ganesh-titan,
Thanks for the updates.
