### ISSUE TITLE
News: Only the 4 post was displayed. All post should be display in the list

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Ascot-Signs#29]
![image](https://cloud.githubusercontent.com/assets/12888048/12257553/b27bfc24-b942-11e5-998a-b9cebe082b76.png)

**Comment by romatitan** [comment]
Can't verify, because of this related issue #

**Comment by ganesh-titan** [comment]
#54 Updated.
As per Enhancement Request pagination added. #31 
Thank you.
