### ISSUE TITLE
Upload form: If the "Select File" field has an error prompt, the file name will not appear on that field.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Ascot-Signs#70]
Step to Replicate:
1.Go to Upload page, and click the upload button to open the form
2. Leave the field blank
3. Click Submit button
4. Observe that the field placeholder is now missing.
5. Click the Select field to open the file window
6. Choose and click any file, then click open to upload
7. Observe that after clicking the "Open" button from the file window, the file name did not appear on the select field.

![image](https://cloud.githubusercontent.com/assets/12888048/12439352/82abfd68-bf6a-11e5-9916-c3200bf304d7.png)

**Comment by ganesh-titan** [comment]
FYI: As per PM request Upload form functionality has been updated.
see sreenshot below for reference.
![untitled-3](https://cloud.githubusercontent.com/assets/13450883/12503912/ba52d5ee-c0fe-11e5-9c69-684b34ae4379.jpg)

once re-check bug no: #69 for closing.  
Thank You.
