### ISSUE TITLE
Homepage - devices: Project title was aligned to middle (vertically-center)

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Ascot-Signs#89]
Device: ipad Air, S4, ipodtouch5 - (portrait)

with 1 line post title
![image](https://cloud.githubusercontent.com/assets/12888048/12605826/6f84ae3a-c503-11e5-9666-4f5fc534163b.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/12633508/6d8812e8-c5ad-11e5-9252-5199a2bad220.png)

**Comment by ganesh-titan** [comment]
Updated. Check once again.
